.gitignore, README.md, config.sample.php, data/manager_routes.php, src/UNL/UCBCN.php, src/UNL/UCBCN/ActiveRecord/Record.php, src/UNL/UCBCN/Calendar.php, src/UNL/UCBCN/Calendar/Event.php, src/UNL/UCBCN/Calendars.php, src/UNL/UCBCN/Event.php, src/UNL/UCBCN/Events.php, src/UNL/UCBCN/Manager/Auth.php, src/UNL/UCBCN/Manager/Calendar.php, src/UNL/UCBCN/Manager/CalendarList.php, src/UNL/UCBCN/Manager/Controller.php, src/UNL/UCBCN/Manager/OutputController.php, src/UNL/UCBCN/User.php, www/index.php, www/manager/index.php, www/sample.htaccess, www/templates/default/html/manager/Calendar.tpl.php, www/templates/default/html/manager/CalendarList.tpl.php, www/templates/default/html/manager/Controller.tpl.php, www/templates/default/html/manager/Exception.tpl.php
This contains the /calendar/manage/ view and some other basic stuff to get us up and running.
=> Some base code

src/UNL/UCBCN/Manager/Auth.php, src/UNL/UCBCN/Manager/Calendar.php, src/UNL/UCBCN/Manager/CalendarList.php, src/UNL/UCBCN/Manager/CreateEvent.php, tmp/.gitignore
* implement single log out
* use a central method for getting the current user
=> Improve auth

composer.json, composer.lock, src/UNL/UCBCN/Manager/Controller.php, www/templates/default/html/Controller.tpl.php, www/templates/default/html/manager/Controller.tpl.php, www/templates/default/html/manager/navigation.tpl.php
This gives us some advantages:
* Easy to maintain updates to the framework
* Less framework clutter in the template
=> Use the php unl template library to include the framework

config.sample.php, data/manager_routes.php, src/UNL/UCBCN.php, src/UNL/UCBCN/Calendar.php, src/UNL/UCBCN/Calendar/Subscription.php, src/UNL/UCBCN/Calendar/SubscriptionHasCalendar.php, src/UNL/UCBCN/Event.php, src/UNL/UCBCN/Events.php, src/UNL/UCBCN/Manager/Calendar.php, src/UNL/UCBCN/Manager/CreateEvent.php, src/UNL/UCBCN/Manager/CreateSubscription.php, src/UNL/UCBCN/Manager/DeleteSubscription.php, www/templates/default/html/manager/CreateSubscription.tpl.php, www/templates/default/html/manager/Subscription.tpl.php
https://trello.com/c/xfKk7DQq
https://trello.com/c/UEFFrJTE
https://trello.com/c/aq0Ptwqd
=> 3 New Features

src/UNL/UCBCN/Manager/DeleteSubscription.php
=> Fix deleting subscriptions

www/templates/default/html/manager/AddUser.tpl.php
We have had several support emails asking how to add someone to the list of users.  This will hopefully clarify things.
=> Add a little help text to the add user list

www/templates/default/html/Controller.tpl.php
=> Change wording

src/UNL/UCBCN/Events.php
Updated the manager events search query in Events class. Manager can now search events by event title, event description, event type, event location or event date.
=> Update manager event search query

src/UNL/UCBCN/Frontend/Controller.php, www/templates/default/html/Controller.tpl.php, www/templates/default/html/manager/Controller.tpl.php
Will help ensure css and js are up-to-date
=> Add some basic cache busting for assets

data/manager_routes.php, src/UNL/UCBCN/Event.php, src/UNL/UCBCN/Manager/ViewEvent.php, www/templates/default/html/manager/Calendar.tpl.php, www/templates/default/html/manager/ViewEvent.tpl.php
Nothing super fancy design-wise, just a quick preview of event details including the description and image so that managers can learn more about the event before accepting a recommendation.
=> Allow previewing event details before accepting a recommended event

www/templates/default/html/manager/AddDatetime.tpl.php, www/templates/default/html/manager/AddUser.tpl.php, www/templates/default/html/manager/Calendar.tpl.php, www/templates/default/html/manager/CreateCalendar.tpl.php, www/templates/default/html/manager/CreateEvent.tpl.php, www/templates/default/html/manager/EditEvent.tpl.php, www/templates/default/html/manager/Search.tpl.php
The CSS was updated for .dcf-input-select to be in outer div containing select to be directly in select. The change makes selects with div display incorrectly.
=> Move select class from outer div to select tag

www/templates/default/html/css/manager.css, www/templates/default/html/less/manager.less, www/templates/default/html/manager/AddDatetime.tpl.php, www/templates/default/html/manager/CreateEvent.tpl.php
Can test here: http://iimjsturek.unl.edu/UNL_Events/www
=> Update layout for date-time forms to display better in 5.0

www/templates/default/html/Controller.tpl.php, www/templates/default/icalendar/EventInstance.tpl.php
* For ICS file updated UID for event to include recurringdate id for recurring events so UID is unique
* Updated calendar home link to link to current calendar and not always main calendar
=> ICS recurring event bug fix and update calendar home link

www/templates/default/html/manager/Controller.tpl.php
Merge/Push once the `dxg@listserv.unl.edu` address is ready.
=> Update iim listserv email address

www/templates/default/html/MonthWidget.tpl.php
Framework JS expects `<span>` with the class `monthvalue`.
=> Restore <spans> for WDN JS compatibility

src/UNL/UCBCN/Calendar.php
Fixes a memory issue when processing calendar->archiveEvents when passing a large array of event ids. Fix checks the past status of each event and places only event id in an array instead of an entire event object. Also, some arrays are reused instead of having separate arrays.
=> Restructure archiveEvents to prevent memory issues

src/UNL/UCBCN/Account.php, src/UNL/UCBCN/Event.php, src/UNL/UCBCN/Location.php, src/UNL/UCBCN/Util.php
For issue: https://github.com/unl/UNL_Events/issues/122
=> Format phone numbers

www/templates/default/html/sidebar.tpl.php
- Remove stray `</path>` tag
- Add closing tags for `<path>`s and `<circle>`
- Add line breaks
=> Fix closing tags in SVG icon

composer.json, composer.lock, www/templates/default/html/Controller.tpl.php, www/templates/default/html/manager/Calendar.tpl.php, www/templates/default/html/manager/Controller.tpl.php
Do not commit until WDN version 5.3 is available.
=> WIP: Support WDN version 5.3

scripts/image_cleanup.php
The script will be added to a weekly cron job to remove images from past events older than two years ago.
=> Add script to purge images from past events (2 years old)

src/UNL/UCBCN/Event/Occurrence.php, src/UNL/UCBCN/Frontend/Upcoming.php, src/UNL/UCBCN/Manager/AddDatetime.php, src/UNL/UCBCN/Manager/CreateEvent.php, src/UNL/UCBCN/Manager/PostHandler.php, www/templates/default/html/manager/AddDatetime.tpl.php, www/templates/default/html/manager/CreateEvent.tpl.php
This prevents recurring event instances from span different days (ongoing event).
=> Do not allow ongoing recurring events

src/UNL/UCBCN/Frontend/EventListing.php, src/UNL/UCBCN/Frontend/Featured.php, www/templates/default/html/EventListingSummary.tpl.php, www/templates/default/html/manager/EditEvent.tpl.php
To ignore whitespace changes use: https://github.com/unl/UNL_Events/pull/170/files?w=1
To test add a recurring event and edit and/or remove all instances of the recurrence.
You may test on https://events-dev.unl.edu/
=> Handle event instance errors

www/templates/default/html/manager/Calendar.tpl.php, www/templates/default/html/manager/EditEvent.tpl.php, www/templates/default/html/manager/Search.tpl.php
These changes are dependent on WDN rollout with support for DCF pagination.
=> WIP: Implement DCF pagination

www/templates/default/html/manager/CreateEvent.tpl.php, www/templates/default/html/manager/EditEvent.tpl.php
Marcelo accidentally found out that there was some bug with the cancel event checkbox and I went through and cleaned the code up
=> changed how the checkboxes are outputting checked

www/templates/default/html/manager/EditEvent.tpl.php
Fixed recurring events cancelation bug
=> Changed duplicate name

www/templates/default/html/EventListingSummary.tpl.php, www/templates/default/html/less/events.less
The margin isn't being applied between the date and the event details in each Featured Event listing. This presented an opportunity to revisit the Featured Events layout and make it better match the [recent updates](https://github.com/unl/wdntemplates/pull/1673) to the events component in the wdntemplates.
=> Fix and adjust Featured Events layout

data/api_v2_routes.php, src/UNL/UCBCN/APIv2/APICalendar.php, src/UNL/UCBCN/APIv2/APIEvent.php, src/UNL/UCBCN/APIv2/APIEvents.php, src/UNL/UCBCN/APIv2/APIHome.php, src/UNL/UCBCN/Event.php, src/UNL/UCBCN/Frontend/Audience.php, src/UNL/UCBCN/Frontend/EventType.php, src/UNL/UCBCN/Frontend/Search.php
Added events calendar status to the event output and fixed issues with default limits. This will also add the archived events route
=> Api v2 event status

data/api_v2_routes.php, src/UNL/UCBCN/APIv2/APICalendars.php, src/UNL/UCBCN/APIv2/APIHome.php, src/UNL/UCBCN/Calendars.php
Added API route for calendar searching
=> API v2 Calendar Search

data/api_v2_routes.php, src/UNL/UCBCN/APIv2/APIAllCalendars.php, src/UNL/UCBCN/APIv2/APICalendars.php, src/UNL/UCBCN/APIv2/APIEvent.php, src/UNL/UCBCN/APIv2/APIHome.php, src/UNL/UCBCN/Calendars.php, src/UNL/UCBCN/Events.php, src/UNL/UCBCN/Frontend/Search.php
Added new all calendar events search API and renamed all calendar search
=> All calendar search

www/templates/default/icalendar/EventInstance.tpl.php
Webcasts were not added to the output of ics file's location data
=> Added webcasts to ICS file download

www/templates/default/html/filters.tpl.php, www/templates/default/html/js/filters.js
This PR goes along with [DCF#513](https://github.com/digitalcampusframework/dcf/pull/513)
=> Added hidden and removed old dcf-d-none

www/templates/default/html/manager/EventFormImageUpload.tpl.php
=> Added help text for why you can't remove image

src/UNL/UCBCN/APIv2/APIEvent.php, src/UNL/UCBCN/Calendar.php, src/UNL/UCBCN/Frontend/EventInstance.php, www/templates/default/xml/EventInstance.tpl.php
Added recurring data for event outputs
Added link to api-V2 event output
=> Added recurring data to JSON and XML output

www/templates/default/html/EventListingSummary.tpl.php
This is to go along with [WDN#1747](https://github.com/unl/wdntemplates/pull/1747)
Edit: Fix link
=> Remove dcf-uppercase from featured events

src/UNL/UCBCN/APIv2/APIEvent.php
Fixed time mode translation from API v2 to manager create event
=> Added time mode translation

src/UNL/UCBCN/Manager/CreateCalendar.php, www/templates/default/html/manager/CreateCalendar.tpl.php
Delete button was showing up even when user did not have permission to it. 
#215
=> added calendar delete permission checker

src/UNL/UCBCN/Manager/DeleteDateTime.php
Quick fix for users deleting all eventdatetime associated with their event
=> Added check on occurrence deletion

www/templates/default/html/manager/EditEvent.tpl.php
A popup message appears for delete button when only one occurrence remains so the user is unable to delete the last remaining occurrence.
=> Added popup functionality to delete button

src/UNL/UCBCN/Frontend/OutputController.php, src/UNL/UCBCN/Manager/EditEvent.php
Changes:
- Fixed datelastupdated not being updated for events
- Added logic to send correct cache images headers
Closes #213
=> Fixed lastUpdated for events, and added caching logic to images
